### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by taikedz** [5agado/conversation-analyzer#10]
Hello - I'm trying to install this in a fresh Ubuntu environment, downloading miniconda and then running env update

```bash
# Determine miniconda download target
minconda_url="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
miniconda_file="$(basename "$miniconda_url")"

# Download it
wget "$miniconda_url"

# Install it
bash "$miniconda_file"

# This fails, cannot find jpeg=8d=vc10_0
conda env update --file=requirements.txt
```

Result:

```txt
$ conda env update --file=requirements.txt 

Fetching package metadata ...........

ResolvePackageNotFound: 
  - jpeg 8d vc10_0

```

I tried upgrading conda as suggested online

```
$ conda upgrade conda
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/ubuntu/miniconda3:

The following packages will be UPDATED:

    conda: 4.3.31-py36_0 --> 4.4.8-py36_0

Proceed ([y]/n)? y

conda-4.4.8-py 100% |######################################################################################################| Time: 0:00:00   1.10 MB/s
```

Re-running the env setup yields even more resolution errors:

```
$ conda env update --file=requirements.txt 
Solving environment: failed

ResolvePackageNotFound: 
  - tk==8.5.18=vc10_0
  - scipy==0.16.0=np110py34_0
  - jpeg==8d=vc10_0
  - qt==4.8.7=vc10_5
  - msvc_runtime==1.0.1=vc10_0
  - python==3.4.4=1
  - pyyaml==3.11=py34_2
  - libtiff==4.0.6=vc10_1
  - zlib==1.2.8=vc10_2
  - libpng==1.6.17=vc10_1
  - openssl==1.0.2e=vc10_1
  - sip==4.16.9=py34_2
```

I'm not sufficiently conversant in conda to know where it is pulling its packages or how to adjust the version data ; just getting to this stage required a bit of search - a setup section of the readme would be greatly appreciated...!

Any path to resolution would be welcome !

Cheers

**Comment by 5agado** [comment]
Hi @taikedz 

I added *setup.py* plus better README for easy setup and use of scraper and parser, plus I cleaned up *requirements.txt* in case you want to check out the analysis part too.

If you have further problems with unresolved dependencies I suggest to simply try different versions that are available for your machine.

**Comment by taikedz** [comment]
Thanks for looking into this -- unfortunately there are still resolution errors

```
ResolvePackageNotFound: 
  - scikit-learn==0.19.0=py34_0
  - python==3.4.4=1
  - scipy==0.16.0=np110py34_0
```

I have locally resolved this by removing `python` and `pip` (they are already part of the base environment), and removing explicit versions from `scikit-learn` and `scipy` (they pull latest now...)

Is this going to be an issue ? Can you confirm setting this up in a pristine environment works for you?

(I've been having problems getting tokens from the fb session so I have not yet been able to test the consequences of these changes)
