### ISSUE TITLE
WordsCountStats' object has no attribute 'to_csv'

### ISSUE THREAD

**Issue by tdolega** [5agado/conversation-analyzer#16]
Error while running main.py. Is it broken or am I doing something wrong?
```2019-04-14 14:48:31 INFO - Tokens count: 74
2019-04-14 14:48:31 INFO - Distinct tokens count: 55
2019-04-14 14:48:31 INFO - Lexical diversity: 0.74324
2019-04-14 14:48:31 INFO - ----------
Traceback (most recent call last):
  File "src/main.py", line 68, in <module>
    main(sys.argv[1:])
  File "src/main.py", line 56, in main
    mio.saveDfToStatsFolder(conv, stats, 'wordCount.csv')
  File "/home/tdolega/git/conversation-analyzer/src/util/io.py", line 111, in saveDfToStatsFolder
    df.to_csv(os.path.join(statsFolder, filename), index=saveIndex)
AttributeError: 'WordsCountStats' object has no attribute 'to_csv'

**Comment by 5agado** [comment]
You can try to edit [this line](https://github.com/5agado/conversation-analyzer/blob/b95dc933078102674edfea1eae6839c5514df5cd/src/main.py#L56) by replacing `stats` with `stats.wordsCount`. Let me know if it works.

I will double check and fix eventually next days.

**Comment by tdolega** [comment]
Yes it is working now, thanks!
I'm playing with main.py because I'm not sure how to create those notebooks. Unfortunately links in README are dead.

**Comment by 5agado** [comment]
Thanks to you for the PR!
Yeah, I see now that the README links don't have the extension. Will fix later, otherwise you can find them in the top level folder.

The analysis part is less clean and more buggy, was mostly experiments, sorry about that, but happy you are playing with it!
