### ISSUE TITLE
'Invalid loads value' when trying to pass --authors in parsing

### ISSUE THREAD

**Issue by jreimone** [5agado/conversation-analyzer#4]
I attached your example of the --authors argument and invoked the following command:

      python.exe ..\conversation-analyzer\src\util\conversationParser.py --in ..\scrapedChat\myUserID\conversation.pretty.json --out ..\scrapedChat\myUserID\parsedChat --authors {'11234':'SENDER_1', '112345':'SENDER_2'}

But get this error:

      usage: conversationParser.py [-h] --in conversationPath --out outputFile
                             [--authors authors]
      conversationParser.py: error: argument --authors: invalid loads value: "{'11234':'SENDER_1','112345':'SENDER_2'}"

How is the correct syntax?

**Comment by 5agado** [comment]
Fixed the readme example line. Use all double quotes instead (--authors {"11234":"SENDER_1", "112345":"SENDER_2"})
