### ISSUE TITLE
Does this method still work?

### ISSUE THREAD

**Issue by ditchfieldcaleb** [5agado/conversation-analyzer#6]
I can't find any post requests for thread_info.php

**Comment by 5agado** [comment]
I can still see POST request being issued to _https://www.facebook.com/ajax/mercury/thread_info.php?dpr=1_ 
I am not sure what that _dpr_ is used for, I will have to check it out and try it further, but please close the issue if you managed to make everything work by simply getting the necessary parameters from this POST request.

**Comment by 5agado** [comment]
Checked. Method still works.
